Student Information Mangement
RoCS2024/student-information-management-system pull request #6
Opened 2024-03-05 02:08 UTC by katieann7

2024-03-05 09:44 UTC, RoCS2024 requested changes
remove integrated from the project name

2024-03-05 10:48 UTC, katieann7 commented
Done po sir

2024-03-05 11:08 UTC, RoCS2024 commented on student-information-management-application/build.xml
>          <echo message="java doc has been generated!" />
Check project name

2024-03-05 11:09 UTC, RoCS2024 commented on student-information-management-application/ivy.xml
> +        <dependency org="com.oracle.database.jdbc" name="ojdbc11" rev="23.3.0.23.09"/>
where are the test jars?

2024-03-05 11:09 UTC, RoCS2024 commented on student-information-management-application/src/main/java/com/student/information/management/data/connection/ConnectionHelper.java
> +package com.student.information.management.data.connection;
Fill in codes for ConnectionHelper

2024-03-05 11:10 UTC, RoCS2024 commented on student-information-management-application/src/main/java/com/student/information/management/app/facade/student/impl/StudentFacadeImpl.java
> +public class StudentFacadeImpl {
where is implements StudentFacade?

2024-03-05 11:10 UTC, RoCS2024 commented on student-information-management-application/src/main/java/com/student/information/management/data/student/dao/impl/StudentDaoImpl.java
> +public class StudentDaoImpl {
where is implements StudentDao?

2024-03-05 11:10 UTC, RoCS2024 requested changes
see comments

2024-03-06 03:01 UTC, katieann7 commented
Done na po Sir.

2024-03-06 05:46 UTC, RoCS2024 approved these changes

2024-03-06 05:54 UTC, JustineDaveMagnaye approved these changes

2024-03-06 05:55 UTC, merged